# Generated by Django 5.2.4 on 2025-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QueingAppAPI', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
