# Generated by Django 3.1.12 on 2025-07-12 12:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QueingAppAPI', '0003_auto_20250709_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='surname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=8),
        ),
    ]
