// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW4b_j--atuUTJCHWAxqRxpwJD2ZJ1T5A',
    appId: '1:40222817161:web:cb6692ec8e453ced0fbf58',
    messagingSenderId: '40222817161',
    projectId: 'queuing-bd0b4',
    authDomain: 'queuing-bd0b4.firebaseapp.com',
    storageBucket: 'queuing-bd0b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJNl-EFJlRxlqKsV732x35y51mBE_kyIM',
    appId: '1:40222817161:android:a233af6a4f07f7ff0fbf58',
    messagingSenderId: '40222817161',
    projectId: 'queuing-bd0b4',
    storageBucket: 'queuing-bd0b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeX50chDyh7etcb_QQNfM82_-okX5m7EM',
    appId: '1:40222817161:ios:3d09e134edb841310fbf58',
    messagingSenderId: '40222817161',
    projectId: 'queuing-bd0b4',
    storageBucket: 'queuing-bd0b4.firebasestorage.app',
    iosBundleId: 'com.example.queingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeX50chDyh7etcb_QQNfM82_-okX5m7EM',
    appId: '1:40222817161:ios:3d09e134edb841310fbf58',
    messagingSenderId: '40222817161',
    projectId: 'queuing-bd0b4',
    storageBucket: 'queuing-bd0b4.firebasestorage.app',
    iosBundleId: 'com.example.queingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBW4b_j--atuUTJCHWAxqRxpwJD2ZJ1T5A',
    appId: '1:40222817161:web:362a45ca2052b9cc0fbf58',
    messagingSenderId: '40222817161',
    projectId: 'queuing-bd0b4',
    authDomain: 'queuing-bd0b4.firebaseapp.com',
    storageBucket: 'queuing-bd0b4.firebasestorage.app',
  );
}
